# Get List
GET http://localhost:3000/products HTTP/1.1

###

# Get By Id
GET http://localhost:3000/products/1 HTTP/1.1

###

# Create
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "name": "Z 產品",
  "authors": [
    "作者A",
    "作者B",
    "作者C"
  ],
  "company": "博碩文化",
  "photoUrl": "https://api.fnkr.net/testimg/200x200/DDDDDD/999999/?text=img",
  "price": 15800
}

###

# Update
PUT http://localhost:3000/products/eJYA-6UkKyY HTTP/1.1
Content-Type: application/json

{
  "id": "eJYA-6UkKyY",
  "name": "Z1 產品",
  "authors": [
    "作者A",
    "作者B",
    "作者C"
  ],
  "company": "博碩文化",
  "photoUrl": "https://api.fnkr.net/testimg/200x200/DDDDDD/999999/?text=img",
  "price": 15800
}

###

# Delete
DELETE http://localhost:3000/products/eJYA-6UkKyY HTTP/1.1
